# phpIPAM docker container on Raspberri Pi 2/3
# Maintained by somsakc@hotmail.com

version: '2'

services:
  phpipamdb:
       image: jsurf/rpi-mariadb
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - TZ=Asia/Bangkok
       volumes:
         - /home/docker/phpipam/data:/var/lib/mysql
       networks:
         - phpipam-tier
       restart: always

  phpipamap:
       image: mbixtech/arm32v7-phpipam
       environment:
         - PHPIPAM_DB_HOST=phpipamdb
         - PHPIPAM_DB_USER=root
         - PHPIPAM_DB_PASS=passw0rd
         - PHPIPAM_DB_NAME=phpipam
         - TZ=Asia/Bangkok
       networks:
         - phpipam-tier
       ports:
         - "8082:80"
       restart: always
       depends_on:
         - phpipamdb

networks:
  phpipam-tier:
      driver: bridge

